backend/feedback/urls.py
# coding=utf-8
from django.urls import path
from backend.feedback import views

app_name = "feedback"
urlpatterns = [
    path("create/", views.FeedbackCreate.as_view(), name="create"),
    path("single_support/<int:pk>/", views.FeedbackDetail.as_view(), name="feedback_single"),
    path("all_support/", views.FeedbackAdminList.as_view(), name="feedback_admin"),
    path("search/", views.SearchFeedback.as_view(), name="feedback_search"),
    path("", views.FeedbackList.as_view(), name="feedback"),
]

gk/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('news/', include('backend.news.urls')),
    path('calculator/', include('backend.calculator.urls')),
    path('accounts/', include('allauth.urls')),
    path('feedback/', include('backend.feedback.urls')),
    path('', include('backend.profile.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/administrirovanie/admin-allusers.html
{% extends 'base.html' %}

{% block mobile %}
	<!-- Меню и заголовок для мобилы -->
	<div class="const mobile-nav">
		<a href="javascript:;" class="menu-open"></a>
		<h1>
			Администрирование  <!-- Дублировал для мобильной версии -->
		</h1>
	</div>
	<!-- /Меню и заголовок для мобилы -->
{% endblock mobile %}


{% block content %}
			<div class="content">
				<h1>
					Администрирование
				</h1>

                {% include 'include/admin_menu.html' %}


<div class="content-body">
<form method="get" action="{% url 'feedback:feedback_search' %}" class="search-inp">
<input type="text" placeholder="Введите ФИО члена" name="all">
<input type="submit" value="" class="searchbut">
</form>


	<div class="table">
		<table>
			<thead>
				<tr>
					<td>ФИО</td>
					<td>Дата регистрации</td>
					<td>Группа пользователя</td>
				</tr>
			</thead>
			<tbody>
            {% for user in admin_users_list %}
				<tr>
					<td>{{ user.full_name }} <a href="#" class="edit"></a></td>
					<td>{{ user.user.date_joined }}</td>
					<td>Кандидат в пайщики</td>
				</tr>
            {% endfor %}
			</tbody>
		</table>
	</div>

				</div>
				<div class="paginator">
					<a href="" class="page-prev"></a>
					<a href="">1</a>
					<a href="">2</a>
					<a href="" class="active">3</a>
					<a href="">4</a>
					<a href="">5</a>
					<a href="" class="page-next"></a>
				</div>

			</div>

{% endblock content %}

templates/administrirovanie/admin-allusers_one.html
{% extends 'base.html' %}

{% block mobile %}
	<!-- Меню и заголовок для мобилы -->
	<div class="const mobile-nav">
		<a href="javascript:;" class="menu-open"></a>
		<h1>
			Изменение пользователя  <!-- Дублировал для мобильной версии -->
		</h1>
	</div>
	<!-- /Меню и заголовок для мобилы -->
{% endblock mobile %}


{% block content %}
			<div class="content">
				<h1>
					Изменение пользователя
				</h1>

                {% include 'include/admin_menu.html' %}


<div class="content-body">
		<table class="profile">
			<thead><tr><td colspan="2">Персональные данные</td></tr></thead>
			<tbody>
				<tr>
					<td>ФИО:</td>
					<td><input type="text" value="Иванов Станислав Викторович"></td>
				</tr>
				<tr>
					<td>Мобильный:</td>
					<td><input type="text" value="+79999999999"></td>
				</tr>
				<tr>
					<td>E-mail:</td>
					<td><input type="text" value="admin@mail.ru"></td>
				</tr>
				<tr>
					<td>Номер счета:</td>
					<td>COOP-007-20203232</td>
				</tr>
				<tr>
					<td>Группа пользователя:</td>
					<td>
						<select name="" id="">
							<option value="" selected>Кандидат в пайщики</option>
							<option value="">Пайщик</option>
							<option value="">Распространитель 1ур</option>
							<option value="">Распространитель 2ур</option>
							<option value="">Распространитель 3ур</option>
						</select>
					</td>
				</tr>
				<tr>
					<td>...</td>
					<td>...</td>
				</tr>
				
			</tbody>
			<thead><tr><td colspan="2">Адресные данные</td></tr></thead>
			<tbody>
				<tr>
					<td colspan="2"><h3>Адрес регистрации</h3></td>
				</tr>
				<tr>
					<td>Страна:</td>
					<td>
						<select name="" id="">
							<option value="">Выберите страну</option>
							<option value="">Россия</option>
							<option value="">Украина</option>
						</select>
					</td>
				</tr>
				<tr>
					<td>Регион:</td>
					<td>
						<select name="" id="">
							<option value="">Выберите регион</option>
							<option value="">Россия</option>
							<option value="">Украина</option>
						</select>
					</td>
				</tr>
				<tr>
					<td>Город:</td>
					<td>
						<select name="" id="">
							<option value="">Выберите город</option>
							<option value="">Россия</option>
							<option value="">Украина</option>
						</select>
					</td>
				</tr>
				<tr>
					<td>Улица:</td>
					<td>
						<input type="text" placeholder="Полное название улицы">
					</td>
				</tr>
				<tr>
					<td>Дом:</td>
					<td>
						<input type="text" placeholder="Номер дома">
					</td>
				</tr>
				<tr>
					<td>Корпус:</td>
					<td>
						<input type="text" placeholder="Если есть">
					</td>
				</tr>
				<tr>
					<td>Квартира:</td>
					<td>
						<input type="text" placeholder="Номер квартиры">
					</td>
				</tr>
				<tr>
					<td>Индекс:</td>
					<td>
						<input type="text" placeholder="XXXXXX">
					</td>
				</tr>
				<tr>
					<td colspan="2"><h3>Адрес фактического проживания</h3></td>
				</tr>
				<tr>
					<td>Страна:</td>
					<td>
						<select name="" id="">
							<option value="">Выберите страну</option>
							<option value="">Россия</option>
							<option value="">Украина</option>
						</select>
					</td>
				</tr>
				<tr>
					<td>Регион:</td>
					<td>
						<select name="" id="">
							<option value="">Выберите регион</option>
							<option value="">Россия</option>
							<option value="">Украина</option>
						</select>
					</td>
				</tr>
				<tr>
					<td>Город:</td>
					<td>
						<select name="" id="">
							<option value="">Выберите город</option>
							<option value="">Россия</option>
							<option value="">Украина</option>
						</select>
					</td>
				</tr>
				<tr>
					<td>Улица:</td>
					<td>
						<input type="text" placeholder="Полное название улицы">
					</td>
				</tr>
				<tr>
					<td>Дом:</td>
					<td>
						<input type="text" placeholder="Номер дома">
					</td>
				</tr>
				<tr>
					<td>Корпус:</td>
					<td>
						<input type="text" placeholder="Если есть">
					</td>
				</tr>
				<tr>
					<td>Квартира:</td>
					<td>
						<input type="text" placeholder="Номер квартиры">
					</td>
				</tr>
				<tr>
					<td>Индекс:</td>
					<td>
						<input type="text" placeholder="XXXXXX">
					</td>
				</tr>
				<tr>
					<td>...</td>
					<td>
						...
					</td>
				</tr>
			</tbody>
			<thead><tr><td colspan="2">Анкета</td></tr></thead>
			<tbody>
				<tr>
					<td>Образование:</td>
					<td>
						<select name="" id="">
							<option value="">Высшее</option>
							<option value="">Среднее</option>
							<option value="">Низшее</option>
						</select>
					</td>
				</tr>
				<tr>
					<td>...</td>
					<td>
						...
					</td>
				</tr>
			</tbody>
			<thead><tr><td colspan="2">Безопасность</td></tr></thead>
			<tbody>
				<tr>
					<td>Старый пароль:</td>
					<td>
						<input type="password" name="" id="">
					</td>
				</tr>
				<tr>
					<td>Новый пароль:</td>
					<td>
						<input type="password" name="" id="">
					</td>
				</tr>
				<tr>
					<td>Повторите пароль:</td>
					<td>
						<input type="password" name="" id="">
					</td>
				</tr>
			</tbody>
		</table>
		<input type="button" value="Сохранить" class="savebut">
		<div class="info"><img src="img/information.svg" alt="">Изменения сохранены</div>
	</div>
				</div>
{% endblock content %}

templates/administrirovanie/admin-podtv.html
{% extends 'base.html' %}

{% block mobile %}
	<!-- Меню и заголовок для мобилы -->
	<div class="const mobile-nav">
		<a href="javascript:;" class="menu-open"></a>
		<h1>
			Администрирование  <!-- Дублировал для мобильной версии -->
		</h1>
	</div>
	<!-- /Меню и заголовок для мобилы -->
{% endblock mobile %}


{% block content %}
			<div class="content">
				<h1>
					Администрирование
				</h1>

				{% include 'include/admin_menu.html' %}


<div class="content-body">
<form method="get" action="{% url 'feedback:feedback_search' %}" class="search-inp">
<input type="text" placeholder="Введите ФИО члена" name="pay">
<input type="submit" value="" class="searchbut">
</form>


	<div class="table">
		<table>
			<thead>
				<tr>
					<td>ФИО</td>
					<td>Группа</td>
					<td>Тип платежа</td>
					<td>Дата отправки платежа</td>
					<td>Действия</td>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>Иванов Аркадий Иванович</td>
					<td>Кандидат в пайщики</td>
					<td>Вступительный взнос</td>
					<td>11:44 29.04.2020</td>
					<td><a href="">Посмотреть</a></td>
				</tr>
				<tr>
					<td>Иванов Аркадий Иванович</td>
					<td>Кандидат в пайщики</td>
					<td>Вступительный взнос</td>
					<td>11:44 29.04.2020</td>
					<td><a href="">Посмотреть</a></td>
				</tr>
				<tr>
					<td>Иванов Аркадий Иванович</td>
					<td>Кандидат в пайщики</td>
					<td>Вступительный взнос</td>
					<td>11:44 29.04.2020</td>
					<td><a href="">Посмотреть</a></td>
				</tr>
				<tr>
					<td>Иванов Аркадий Иванович</td>
					<td>Кандидат в пайщики</td>
					<td>Вступительный взнос</td>
					<td>11:44 29.04.2020</td>
					<td><a href="">Посмотреть</a></td>
				</tr>
				<tr>
					<td>Иванов Аркадий Иванович</td>
					<td>Кандидат в пайщики</td>
					<td>Вступительный взнос</td>
					<td>11:44 29.04.2020</td>
					<td><a href="">Посмотреть</a></td>
				</tr>
				<tr>
					<td>Иванов Аркадий Иванович</td>
					<td>Кандидат в пайщики</td>
					<td>Вступительный взнос</td>
					<td>11:44 29.04.2020</td>
					<td><a href="">Посмотреть</a></td>
				</tr>
				<tr>
					<td>Иванов Аркадий Иванович</td>
					<td>Кандидат в пайщики</td>
					<td>Вступительный взнос</td>
					<td>11:44 29.04.2020</td>
					<td><a href="">Посмотреть</a></td>
				</tr>		
			</tbody>
		</table>
	</div>

				</div>
				<div class="paginator">
					<a href="" class="page-prev"></a>
					<a href="">1</a>
					<a href="">2</a>
					<a href="" class="active">3</a>
					<a href="">4</a>
					<a href="">5</a>
					<a href="" class="page-next"></a>
				</div>

			</div>
{% endblock content %}

templates/administrirovanie/admin-podtv_one.html
{% extends 'base.html' %}

{% block mobile %}
	<!-- Меню и заголовок для мобилы -->
	<div class="const mobile-nav">
		<a href="javascript:;" class="menu-open"></a>
		<h1>
			Подтверждение платежа  <!-- Дублировал для мобильной версии -->
		</h1>
	</div>
	<!-- /Меню и заголовок для мобилы -->
{% endblock mobile %}


{% block content %}
			<div class="content">
				<h1>
					Подтверждение платежа
				</h1>

				{% include 'include/admin_menu.html' %}

<div class="content-body">
	<a href="https://opt-1334847.ssl.1c-bitrix-cdn.ru/upload/medialibrary/0b8/0b8d761e41dfa8e9439f6ecd214f0946.JPG" target="_blank">Открыть чек в новом окне</a>

	<img src="https://opt-1334847.ssl.1c-bitrix-cdn.ru/upload/medialibrary/0b8/0b8d761e41dfa8e9439f6ecd214f0946.JPG" alt="" class="verif-img">

	<form action="">
		<label>Комментарий</label>
		<!--Если нажали кнопку сообщить об ошибке, комментарий подставляется в поле "Статус" на странице платежей у пользователя. Если нажали подтвердить, то в статус добавляется подобное "Подтвержден. 12:00 25.08.2020"-->
		<textarea name="" id="" cols="30" rows="10"></textarea>
		<input type="button" value="Подтвердить" class="savebut" style="margin-right:20px"><input type="button" value="Сообщить об ошибке" class="erorbut">
	</form>

				</div>

			</div>
{% endblock content %}

templates/administrirovanie/admin-support.html
{% extends 'base.html' %}

{% block mobile %}
    <!-- Меню и заголовок для мобилы -->
    <div class="const mobile-nav">
        <a href="javascript:;" class="menu-open"></a>
        <h1>
            Администрирование  <!-- Дублировал для мобильной версии -->
        </h1>
    </div>
    <!-- /Меню и заголовок для мобилы -->
{% endblock mobile %}


{% block content %}
    <div class="content">
        <h1>
            Администрирование
        </h1>

        {% include 'include/admin_menu.html' %}


        <div class="content-body">
            <form method="get" action="{% url 'feedback:feedback_search' %}" class="search-inp">
                <input type="text" placeholder="Введите ФИО члена" name="qus">
                <input type="submit" value="" class="searchbut">
            </form>


            <div class="table">
                <table>
                    <thead>
                    <tr>
                        <td>ФИО</td>
                        <td>Дата вопроса</td>
                        <td>Заголовок вопроса</td>
                        <td>Вопрос</td>
                        <td>Статус</td>
                        <td>Действия</td>
                    </tr>
                    </thead>
                    <tbody>
                    {% for support in object_list %}
                        <tr>
                            <td>{{ support.user.profile.full_name }}</td>
                            <td>{{ support.date }}</td>
                            <td>{{ support.title }}</td>
                            <td>{{ support.text }}</td>
                            {% if support.processing == False %}
                                <td>В ожидании</td>
                            {% else %}
                                <td>Рассмотрено</td>
                            {% endif %}
                            <td><a href="{{ support.get_absolute_url }}">Посмотреть</a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>

        </div>
        {% if is_paginated %}
            {% include 'include/pagination.html' %}
        {% endif %}

    </div>
{% endblock content %}

templates/administrirovanie/admin-verif.html
{% extends 'base.html' %}

{% block mobile %}
	<!-- Меню и заголовок для мобилы -->
	<div class="const mobile-nav">
		<a href="javascript:;" class="menu-open"></a>
		<h1>
			Администрирование  <!-- Дублировал для мобильной версии -->
		</h1>
	</div>
	<!-- /Меню и заголовок для мобилы -->
{% endblock mobile %}


{% block content %}
			<div class="content">
				<h1>
					Администрирование
				</h1>

				{% include 'include/admin_menu.html' %}


<div class="content-body">
<form method="get" action="{% url 'feedback:feedback_search' %}" class="search-inp">
<input type="text" placeholder="Введите ФИО члена" name="wait">
<input type="submit" value="" class="searchbut">
</form>


	<div class="table">
		<table>
			<thead>
				<tr>
					<td>ФИО</td>
					<td>Группа</td>
					<td>Тип</td>
					<td>Статус</td>
					<td>Действия</td>
				</tr>
			</thead>
			<tbody>
            {% for ver in verification_list %}
				<tr>
					<td>{{ ver.user.profile.full_name }}</td>
					<td>Кандидат в пайщики</td>
					<td>Документ на вступление</td>
					<td>В ожидании</td>
					<td><a href="">Посмотреть</a></td>
				</tr>
            {% endfor %}
				<tr>
					<td>Иванов Аркадий Иванович</td>
					<td>Кандидат в пайщики</td>
					<td>Фотоверификация</td>
					<td>В ожидании</td>
					<td><a href="">Посмотреть</a></td>
				</tr>
				<tr>
					<td>Иванов Аркадий Иванович</td>
					<td>Кандидат в пайщики</td>
					<td>Документ на вступление</td>
					<td>В ожидании</td>
					<td><a href="">Посмотреть</a></td>
				</tr>
				
			</tbody>
		</table>
	</div>

				</div>
				<div class="paginator">
					<a href="" class="page-prev"></a>
					<a href="">1</a>
					<a href="">2</a>
					<a href="" class="active">3</a>
					<a href="">4</a>
					<a href="">5</a>
					<a href="" class="page-next"></a>
				</div>

			</div>
{% endblock content %}

templates/administrirovanie/admin-verif_one.html
{% extends 'base.html' %}

{% block mobile %}
	<!-- Меню и заголовок для мобилы -->
	<div class="const mobile-nav">
		<a href="javascript:;" class="menu-open"></a>
		<h1>
			Верификация  <!-- Дублировал для мобильной версии -->
		</h1>
	</div>
	<!-- /Меню и заголовок для мобилы -->
{% endblock mobile %}


{% block content %}
			<div class="content">
				<h1>
					Верификация
				</h1>

				{% include 'include/admin_menu.html' %}

<div class="content-body">
	<a href="https://gendocs.ru/gendocs/docs/39/38451/conv_1/file1_html_mcbe73d0.jpg" target="_blank">Открыть в новом окне</a>

	<!--Если файл-картинка, то можно показать превью-->
	<img src="https://gendocs.ru/gendocs/docs/39/38451/conv_1/file1_html_mcbe73d0.jpg" alt="" class="verif-img">

	<form action="">
		<label>Комментарий</label>
		<!--Если нажали кнопку сообщить об ошибке, комментарий подставляется в поле "Статус" на странице документов у пользователя. Если нажали верифицировать, то в статус добавляется подобное "Проверен. 12:00 25.08.2020"-->
		<textarea name="" id="" cols="30" rows="10"></textarea>
		<input type="button" value="Верифицировать" class="savebut" style="margin-right:20px"><input type="button" value="Сообщить об ошибке" class="erorbut">
	</form>

				</div>

			</div>
{% endblock content %}