backend/feedback/urls.py
# coding=utf-8
from django.urls import path
from backend.feedback import views

app_name = "feedback"
urlpatterns = [
    path("create/", views.FeedbackCreate.as_view(), name="create"),
    path("single_support/<int:pk>/", views.FeedbackDetail.as_view(), name="feedback_single"),
    path("all_support/", views.FeedbackAdminList.as_view(), name="feedback_admin"),
    path("search/", views.SearchFeedback.as_view(), name="feedback_search"),
    path("", views.FeedbackList.as_view(), name="feedback"),
]

gk/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('news/', include('backend.news.urls')),
    path('calculator/', include('backend.calculator.urls')),
    path('accounts/', include('allauth.urls')),
    path('feedback/', include('backend.feedback.urls')),
    path('', include('backend.profile.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/feedback/models.py
import os

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

from .send_mail import send_mail_feedback
from django.urls import reverse


def get_path_img_feedback(instanse, file):

    end_extention = file.split('.')[-1]
    head = file.split('.')[0]
    if len(head) > 10:
        head = head[:10]
    file_name = head + '.' + end_extention
    return os.path.join('feedback', 'img_{}').format(file_name)


class Feedback(models.Model):
    """Модель обратной связи"""
    user = models.ForeignKey(User, verbose_name="Кто отправил", on_delete=models.CASCADE, blank=True, null=True)
    title = models.CharField("Заголовок", max_length=50)
    text = models.TextField("Содержание вопроса", max_length=1000)
    image = models.ImageField("Фото/Скриншот", upload_to=get_path_img_feedback)
    date = models.DateField("Дата добавления", auto_now=True)
    processing = models.BooleanField("Обработано?", default=False)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("feedback:feedback_single", kwargs={"pk": self.id})

    # def save(self, *args, **kwargs):
    #     super().save(*args, **kwargs)
        # send_mail_feedback(self.user.profile.full_name)

    class Meta:
        verbose_name = "Обратная связь"
        verbose_name_plural = "Обратные связи"
        ordering = ["-date"]


# @receiver(post_save, sender=Feedback)
# def create_user_mess(sender, instance, created, **kwargs):
#     """Отправка сообщения на обратной связи на email"""
#     if created:
#         send_mail_feedback(instance.user)

backend/feedback/forms.py
from django import forms
from .models import Feedback


class FeedbackForm(forms.ModelForm):
    """Форма обратной связи"""

    class Meta:
        model = Feedback
        fields = ("title", "text", "image")

backend/feedback/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, render
from django.views.generic import ListView, CreateView, DetailView, View

from backend.profile.models import Profile
from .models import Feedback
from .forms import FeedbackForm


class FeedbackList(LoginRequiredMixin, ListView):
    """Список обратных связей"""
    paginate_by = 6
    template_name = "feedback/feedback_list.html"

    def get_queryset(self):
        if self.request.user.is_superuser:
            return Feedback.objects.all()
        return Feedback.objects.filter(user=self.request.user)


class FeedbackAdminList(LoginRequiredMixin, ListView):
    """Список обратных связей в адменистрированнии"""
    paginate_by = 6
    template_name = "administrirovanie/admin-support.html"

    def get_queryset(self):
        return Feedback.objects.all()

    # def get_context_data(self, *, object_list=None, **kwargs):
    #     return Feedback.objects.filter(user__username=self.request.GET.get('qus'))


class FeedbackDetail(LoginRequiredMixin, DetailView):
    """Детально о запросе"""
    model = Feedback
    context_object_name = 'single_support'

    def get_object(self, queryset=None):
        obj = get_object_or_404(Feedback, id=self.kwargs.get('pk'))
        return obj


# class SearchFeedback(LoginRequiredMixin, ListView):
#     """Поиск пользователей по ФИО"""
#     paginate_by = 5
#     template_name = "administrirovanie/admin-support.html"
#
#     def get_queryset(self):
#         return Feedback.objects.filter(user__username=self.request.GET.get('qus'))


class SearchFeedback(LoginRequiredMixin, View):
    """Поиск пользователей по ФИО"""
    def get(self, request):
        all_users = {'admin_users_list': Profile.objects.filter(full_name=self.request.GET.get('all'))}
        verification = {'verification_list': Profile.objects.filter(full_name=self.request.GET.get('wait'))}
        paying = {'pay_list': Profile.objects.filter(full_name=self.request.GET.get('pay'))}
        support = {'object_list': Feedback.objects.filter(user__username=self.request.GET.get('qus'))}
        if self.request.GET.get('all'):
            return render(self.request, 'administrirovanie/admin-allusers.html', all_users)
        elif self.request.GET.get('wait'):
            return render(self.request, 'administrirovanie/admin-verif.html', verification)
        elif self.request.GET.get('pay'):
            return render(self.request, 'administrirovanie/admin-podtv.html', paying)
        elif self.request.GET.get('qus'):
            return render(self.request, 'administrirovanie/admin-support.html', support)


class FeedbackCreate(LoginRequiredMixin, CreateView):
    """Добавление обратной связи"""
    model = Feedback
    form_class = FeedbackForm
    # template_name = 'feedback/feedback_list.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        # self.success_url = form.instance.get_absolute_url()
        # form.save()
        message = 'Отправлено в службу поддержки.'
        messages.success(self.request, message)
        return super(FeedbackCreate, self).form_valid(form)

templates/feedback/feedback_detail.html
{% extends 'base.html' %}
{% load static %}

{% block mobile %}
    <!-- Меню и заголовок для мобилы -->
    <div class="const mobile-nav">
        <a href="javascript:;" class="menu-open"></a>
        <h1>
            Техподдержка  <!-- Дублировал для мобильной версии -->
        </h1>
    </div>
    <!-- /Меню и заголовок для мобилы -->
{% endblock mobile %}


{% block content %}
    <div class="content">
        <h1>
            Техподдержка
        </h1>

        {% include 'include/admin_menu.html' %}

        <div class="content-body">
            <div class="table">
                <table>
                    <thead>
                    <tr>
                        <td>ФИО</td>
                        <td>Дата вопроса</td>
                        <td>Заголовок вопроса</td>
                        <td>Вопрос</td>
                        <td>Статус</td>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td>{{ single_support.user }}</td>
                        <td>{{ single_support.date }}</td>
                        <td>{{ single_support.title }}</td>
                        <td>{{ single_support.text }}</td>
                        {% if single_support.processing == False %}
                            <td>В ожидании</td>
                        {% else %}
                            <td>Рассмотрено</td>
                        {% endif %}
                    </tr>
                    </tbody>
                </table>
            </div>
            <br><br>
            <form action="">
                <label>Ответ</label>
                <textarea name="" id="" cols="30" rows="10"></textarea>
                <input type="button" value="Ответить" class="savebut" style="margin-right:20px">
            </form>
        </div>
    </div>
{% endblock content %}

templates/feedback/feedback_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <div class="content">
        <h1>
            Служба поддержки
        </h1>

        <div class="content-body">
            <form method="POST" action="{% url 'feedback:create' %}" enctype="multipart/form-data">
                {% csrf_token %}
                <label>Заголовок вопроса:</label>
                <input type="text" name="title" required placeholder="Макс. 50 символов"><br>
                <label>Содержание вопроса:</label><br>
                <textarea name="text" id="" required placeholder="А вот тут максимально подробно"></textarea>
                <label>Приложите фото/скриншот:</label><br><br>
                <div class="file-inp">
                    <label><input type="file" name="image" required><span>Выберите файл</span></label>
                </div>
                <input type="submit" value="Отправить запрос" class="savebut">
            </form>
            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        <div class="info"><img src="{% static 'img/information.svg' %}" alt="">{{ message }}</div>
                    {% endfor %}
                </ul>
            {% endif %}
            <div class="table">
                <table>
                    <thead>
                    <tr>
                        <td>Заголовок вопроса</td>
                        <td>Содержание вопроса</td>
                        <td>Дата</td>
                        <td>Ответ</td>
                    </tr>
                    </thead>
                    {% for feedback in feedback_list %}
                        <tbody>
                        <tr>
                            <td>{{ feedback.title }}</td>
                            <td>{{ feedback.text }}</td>
                            <td>{{ feedback.date }}</td>
                            {% if feedback.processing == True %}
                                <td style="max-width:300px;"><span style="color:green">Обработано</span></td>
                            {% else %}
                                <td style="max-width:300px;"><span style="color:blue">В обработке</span></td>
                            {% endif %}
                        </tr>
                        </tbody>
                    {% endfor %}
                </table>
            </div>
            {#                        <div class="info"><img src="{% static 'img/information.svg' %}" alt="">Отправлено в службу поддержки</div>#}
            {#            <div class="error"><img src="{% static 'img/error.svg' %}" alt="">Ошибка отправки. Не заполнено содержание вопроса#}
            {#            </div>#}
{#            {% feedback_list count=4 %}#}
{#            {% paginate 20 entries %}#}
{#            {% if count %}#}
            {% include 'include/pagination.html' %}
{#            {% endif %}#}
        </div>
    </div>
{% endblock %}